In [4]:
# NumPy Fundamentals - Student Lab

## Lab Instructions

"""Complete all exercises below. Write your code in a Python file or Jupyter notebook. Test each task to ensure it produces the expected output.

**Assessment Criteria:**
- Code correctness and functionality
- Proper use of NumPy functions
- Code efficiency (use vectorized operations)
- Clean, readable code with appropriate comments

"""

'Complete all exercises below. Write your code in a Python file or Jupyter notebook. Test each task to ensure it produces the expected output.\n\n**Assessment Criteria:**\n- Code correctness and functionality\n- Proper use of NumPy functions\n- Code efficiency (use vectorized operations)\n- Clean, readable code with appropriate comments\n\n'

In [8]:
## Exercise 1: Array Creation and Attributes (15 points)

### Task 1.1: Create arrays using different methods (10 points)

"""Write code to create the following arrays:

1. A 1D array containing values from 0 to 9
2. A 2D array (3x3) containing values from 1 to 9
3. A 3x4 array filled with zeros
4. A 2x5 array filled with ones (data type: float32)
5. A 4x4 identity matrix
6. An array with values from 10 to 50 with step size 5
7. An array with 8 evenly spaced values between 0 and 1

**Your Code:**
```python"""
import numpy as np

# Write your code here

## Exercise 1: Array Creation and Attributes
print("="*60)
print("Exercise 1: Creating arrays using different methods")
print("="*60)
#--------------------------------------------
#Task 1.1: Create arrays using different methods
#--------------------------------------------
print("\n--- Task 1.1: Create arrays using different methods ---")
# 1. 1D array containing values from 0 to 9
print("\n1. 1D array containing values from 0 to 9")
arr1= np.arange(10) #arange gives values in range
print(arr1)
# 2. A 2D array (3x3) containing values from 1 to 9
print("\n2. 2D array (3x3) containing values from 1 to 9")
arr2 = np.arange(1,10).reshape(3, 3) #3X3 matrix wj=hich contain elements from 1 to 9
print(arr2)
# 3. A 3x4 array filled with zeros
print("\n3. 3x4 array filled with zeros")
arr3 = np.zeros((3,4)) #3X4 matrix of null values
print(arr3)
# 4. A 2x5 array filled with ones (data type: float32)
print("\n4. 2x5 array filled with ones (data type: float32)")
arr4 = np.ones((2,5))
arr4 = arr4.astype(np.float32)
print(arr4)
# 5. A 4x4 identity matrix
print("\n5. A 4x4 identity matrix")
arr5 = np.eye(4) #to get identity matrix
print(arr5)
# 6. An array with values from 10 to 50 with step size 5
print("\n6. An array with values from 10 to 50 with step size 5")
arr6 = np.arange(10,51,5) #ranges from 10 to 50
print(arr6)
# 7. An array with 8 evenly spaced values between 0 and 1
# used gtp to know evenly space values and linspace
print("\n7. An array with 8 evenly spaced values between 0 and 1")
arr7 = np.linspace(0,1,8) #give exact number of values
print(arr7)

Exercise 1: Creating arrays using different methods

--- Task 1.1: Create arrays using different methods ---

1. 1D array containing values from 0 to 9
[0 1 2 3 4 5 6 7 8 9]

2. 2D array (3x3) containing values from 1 to 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3. 3x4 array filled with zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

4. 2x5 array filled with ones (data type: float32)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

5. A 4x4 identity matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

6. An array with values from 10 to 50 with step size 5
[10 15 20 25 30 35 40 45 50]

7. An array with 8 evenly spaced values between 0 and 1
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [10]:
### Task 1.2: Explore array attributes (5 points)

"""Create a 3x4 array with values from 1 to 12. Print the following attributes:
- Shape
- Number of dimensions
- Total number of elements
- Data type
- Item size in bytes
- Total bytes consumed

**Your Code:**
```python"""
# Write your code here
#--------------------------------------------
# Task 1.2: Explore array attributes
#--------------------------------------------
print("\n----Task 1.2: Explore array attributes----")

# creating array in the range of 1 to 12 and reshaping it to 3X4
arr = np.arange(1,13).reshape(3, 4)

# displaying array
print("\nArray:\n",arr)
# number of row and columns
print("\nshape:",arr.shape)
# returns dimentions
print("\nnumber of dimentions:",arr.ndim)
# total number of elements
print("\nTotal number of elements:",arr.size)
#type of elements in array 
print("\nData type:",arr.dtype)
# total bytes consumed
print("\nTotal bytes consumed:",arr.nbytes) 



----Task 1.2: Explore array attributes----

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)

number of dimentions: 2

Total number of elements: 12

Data type: int64

Total bytes consumed: 96


In [12]:

## Exercise 2: Indexing and Slicing (20 points)
### Task 2.1: Basic indexing (5 points)

"""Given the array: `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])`

Write code to:
1. Access the first element
2. Access the last element using negative indexing
3. Access the 5th element

Then create a 2D array with shape (3, 4) and:
- Access the element at row 1, column 2
- Access the element at row 0, column 3
- Access the last element

**Your Code:**
```python"""

# Write your code here

## Exercise 2: Indexing and Slicing
print("="*60)
print("Exercise 2: Indexing and Slicing")
print("="*60)
#-----------------------------
## Task 2.1: Basic indexing
#-----------------------------
print("\n---Task 2.1: Basic indexing---")

#given array
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("\nGiven array:",arr1)
# 1. Accessing the first element
print("\nfirst element:", arr1[0])
# 2. Accessing the last element using negative indexing
print("\nLast element:", arr1[-1])
# 3. Accessing the 5th element
print("\nFifth element:", arr1[4])

# creating a 2D array with shape (3, 4)
print("\n2D array:")
arr2 = np.arange(1, 13).reshape(3, 4) #shaping array into 3X4
print(arr2)
print("\nelement at row 1, column 2:",arr2[1, 2]) #row index1 and column index2
print("\nelement at row 0, column 3:",arr2[0,3])
# used gpt to get the last element
print("\nlast element:",arr2[-1, -1])


Exercise 2: Indexing and Slicing

---Task 2.1: Basic indexing---

Given array: [ 10  20  30  40  50  60  70  80  90 100]

first element: 10

Last element: 100

Fifth element: 50

2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

element at row 1, column 2: 7

element at row 0, column 3: 4

last element: 12


In [14]:
### Task 2.2: Slicing operations (8 points)
"""
Given `arr = np.arange(0, 20)`:

1. Extract elements from index 5 to 15 (inclusive)
2. Extract every 3rd element from the array
3. Reverse the entire array using slicing

Create a 4x4 2D array and:
- Extract the first 2 rows and first 3 columns
- Extract the last 2 rows and last 2 columns
- Extract every other row with all columns

**Your Code:**
```python
"""
# Write your code here

#-----------------------------------
## Task 2.2: Slicing operations
#-----------------------------------
print("\n---Task 2.2: Slicing operations---")
# Given array in the range of 0 to 20
arr1 = np.arange(0, 20)
print("\nOriginal array:\n",arr)

# 1. Extracting elements from index 5 to 15 (inclusive)
print("\nElements from index 5 to 15:\n",arr1[5:16]) # by using slicing

# 2. Extracting every 3rd element from the array
print("\nExtracting every 3rd element from the array:")
print(arr1[::3]) #star = 0, stop = n, step = 3

# 3. Reverse the entire array using slicing
print("\nReversing the entire array using slicing:")
print(arr1[::-1]) # reverse array

# 4x4 2D array
arr2 = np.arange(1,17).reshape(4, 4)
print("\n4x4 2D array:\n",arr2)
# used gpt to extract the first 2 rows and first 3 columns
print("\nfirst 2 rows and first 3 columns:\n",arr2[:2, :3])
# last 2 rows and last 2 columns
print("\nlast 2 rows and last 2 columns:\n",arr2[-2:, -2:]) #tried own
# every other row with all columns
print("\nevery other row with all columns:\n",arr2[::2,:]) 



---Task 2.2: Slicing operations---

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Elements from index 5 to 15:
 [ 5  6  7  8  9 10 11 12 13 14 15]

Extracting every 3rd element from the array:
[ 0  3  6  9 12 15 18]

Reversing the entire array using slicing:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

4x4 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

first 2 rows and first 3 columns:
 [[1 2 3]
 [5 6 7]]

last 2 rows and last 2 columns:
 [[11 12]
 [15 16]]

every other row with all columns:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


In [15]:
### Task 2.3: Boolean and fancy indexing (7 points)
"""
Given `arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])`:

1. Use boolean indexing to extract all values greater than 20
2. Extract all even numbers
3. Extract values between 10 and 30 (inclusive)
4. Use fancy indexing to extract elements at indices 0, 3, 5, and 8

**Your Code:**
```python
"""    
# Write your code here

#---------------------------------------
## Task 2.3: Boolean and fancy indexing
#---------------------------------------
print("\n---Task 2.3: Boolean and fancy indexing----")
# given array
arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])
print("\nOriginal array:",arr)

# 1.using boolean indexing to extract all values greater than 20
print("\nAll values greater than 20:",arr[arr>20])

# 2. Extracting all even numbers
print("\nAll even numbers:",arr[arr % 2 ==0])

# 3. Extract values between 10 and 30 (inclusive)
print("\nValues between 10 and 30:",arr[(arr>10) & (arr<30)])

# 4. Using fancy indexing to extract elements at indices 0, 3, 5, and 8
print("\nElements at indices 0, 3, 5, and 8:",arr[[0, 3, 5, 8]])



---Task 2.3: Boolean and fancy indexing----

Original array: [15 23  8 42 11 37 19  5 33 28]

All values greater than 20: [23 42 37 33 28]

All even numbers: [ 8 42 28]

Values between 10 and 30: [15 23 11 19 28]

Elements at indices 0, 3, 5, and 8: [15 42 37 33]


In [46]:
## Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)
"""
Given two arrays:
- `arr1 = np.array([10, 20, 30, 40, 50])`
- `arr2 = np.array([5, 10, 15, 20, 25])`

Perform the following operations:
1. Element-wise addition
2. Element-wise subtraction
3. Element-wise multiplication
4. Element-wise division
5. Square each element of arr1

Then perform scalar operations on arr1:
- Add 100 to all elements
- Multiply all elements by 3
- Divide all elements by 10

**Your Code:**
```python
"""
# Write your code here

# Exercise 3: Array Operations
print("="*60)
print("Exercise 3: Array Operations")
print("="*60)
#----------------------------------------
# Task 3.1: Arithmetic operations
#----------------------------------------
print("\n--- Task 3.1: Arithmetic operations ---")
# given arrays
arr1 = np.array([10, 20, 30, 40, 50])
print("\nArray1:",arr1)
arr2 = np.array([5, 10, 15, 20, 25])
print("Arra2:",arr2)

# 1. Element-wise addition
add = arr1 + arr2
print("\nElement-wise addition:\n",add)
# 2. Element-wise subtraction
sub = arr1 - arr2 
print("\nElement-wise subtraction:\n",sub)
# 3. Element-wise multiplication
mul = arr1 * arr2 
print("\nElement-wise multiplication:\n",mul)
# 4. Element-wise division
div = arr1 / arr2
print("\nElement-wise division:\n",div)
# 5. Squaring each element of Array1
print("\nSquare each element of Array1:\n",arr1**2)

# scalar operations on array1
print("\n--- scalar operations on array1 ---")
print("\nOriginal array:",arr1)
# Adding 100 to all elements in array1
print("\nAdding 100 to all elements:",arr1+100)
# Multiplying all elements by 3 in array1
print("\nMultiplying all elements by 3:",arr1 * 3)
# Divide all elements by 10
print("\nDividing all elements by 10:",arr1 / 10)


Exercise 3: Array Operations

--- Task 3.1: Arithmetic operations ---

Array1: [10 20 30 40 50]
Arra2: [ 5 10 15 20 25]

Element-wise addition:
 [15 30 45 60 75]

Element-wise subtraction:
 [ 5 10 15 20 25]

Element-wise multiplication:
 [  50  200  450  800 1250]

Element-wise division:
 [2. 2. 2. 2. 2.]

Square each element of Array1:
 [ 100  400  900 1600 2500]

--- scalar operations on array1 ---

Original array: [10 20 30 40 50]

Adding 100 to all elements: [110 120 130 140 150]

Multiplying all elements by 3: [ 30  60  90 120 150]

Dividing all elements by 10: [1. 2. 3. 4. 5.]


In [47]:
### Task 3.2: Universal functions (7 points)
"""
Given `arr = np.array([1, 4, 9, 16, 25, 36])`:

1. Calculate square root of all elements
2. Calculate exponential (e^x) of all elements
3. Calculate natural logarithm of all elements

Create an array of angles `[0, π/6, π/4, π/3, π/2]` and:
- Calculate sine values
- Calculate cosine values

For the array `[1.23, 2.56, 3.89, 4.12]`:
- Round to nearest integer
- Apply floor operation
- Apply ceiling operation

**Your Code:**
```python
"""    
# Write your code here

#--------------------------------
## Task 3.2: Universal functions
#--------------------------------
print("\n--- Task 3.2: Universal functions ---")
# Given array
arr1 = np.array([1, 4, 9, 16, 25, 36])

print("\nOriginal array:",arr)

# 1. Calculating square root of all elements in the array
print("\nsquare root of all elements:\n",np.sqrt(arr1))

# 2. Calculating exponential (e^x) of all elements in the array
print("\nexponential (e^x) of all elements:\n",np.exp(arr1))

# 3. Calculating natural logarithm of all elements in the array
print("\nnatural logarithm of all elements:\n",np.log(arr1))

# Creating an array of angles [0, π/6, π/4, π/3, π/2]
# used gpt to create array of angles
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print("\nArray of angles:",angles)
# sine and coine  values
print("\nsine values:",np.sin(angles))
print("cosine values:",np.cos(angles))

# Given array to perform operations
arr2 = [1.23, 2.56, 3.89, 4.12]
print("\nGiven array:", arr2)

# Round to nearest integer
print("\nRounded integers:", np.round(arr2))

# floor operation, convert each value in the array to its floor value
print("\nFloor:", np.floor(arr2))

# ceiling operation, convert each value in the array to its ceiling value
print("\nCeiling:", np.ceil(arr2))



--- Task 3.2: Universal functions ---

Original array: [12 45 23 67 34 89 56 78 90 31]

square root of all elements:
 [1. 2. 3. 4. 5. 6.]

exponential (e^x) of all elements:
 [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]

natural logarithm of all elements:
 [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]

Array of angles: [0.         0.52359878 0.78539816 1.04719755 1.57079633]

sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Given array: [1.23, 2.56, 3.89, 4.12]

Rounded integers: [1. 3. 4. 4.]

Floor: [1. 2. 3. 4.]

Ceiling: [2. 3. 4. 5.]


In [48]:
## Exercise 4: Array Manipulation (20 points)

### Task 4.1: Reshaping and transposing (10 points)
"""
Create an array with values from 1 to 12, then:
1. Reshape it to 3x4
2. Reshape it to 2x6
3. Reshape it to 2x2x3 (3D array)
4. Transpose the 3x4 array
5. Flatten the 3x4 array back to 1D

**Your Code:**
```python
"""    
# Write your code here

## Exercise 4: Array Manipulation
print("="*60)
print("Exercise 4: Array Manipulation")
print("="*60)
#----------------------------------------
## Task 4.1: Reshaping and transposing
#----------------------------------------
print("\n--- Task 4.1: Reshaping and transposing ---")
# array with values from 1 to 12
arr = np.arange(1,13)
print("\nOriginal Array:",arr)

# 1. Reshaping array to 3x4
arr_3_by_4 = arr.reshape(3,4)
print("\nReshaping array into 3x4:\n",arr_3_by_4)

# 2. Reshaping array to 2x6
arr_2_by_6 = arr.reshape(2,6)
print("\nReshaping array into 2x6:\n",arr_2_by_6)

# 3. Reshaping array to 2x2x3 (3D array)
arr_3d = arr.reshape(2,2,3)
print("\nReshape array into 2x2x3:\n",arr_3d)

# 4. Transpose the 3x4 array
arr_transpose = arr_3_by_4.T
print("\nTranspose of 3x4 array:\n",arr_transpose)

# 5. Flatten the 3x4 array back to 1D
arr_flatten = arr_3_by_4.flatten()
print("\nFlatten the 3x4 array back to 1D:\n",arr_flatten)


Exercise 4: Array Manipulation

--- Task 4.1: Reshaping and transposing ---

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaping array into 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaping array into 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshape array into 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transpose of 3x4 array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flatten the 3x4 array back to 1D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
### Task 4.2: Stacking and splitting (10 points)
"""    
Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`

1. Stack them vertically to create a 3x3 array
2. Stack them horizontally to create a 1D array

Create an array from 1 to 12 and:
- Split it into 4 equal parts

Create a 4x4 array with values 1-16 and:
- Split it horizontally into 2 parts

**Your Code:**
```python
"""
# Write your code here

#------------------------------------
## Task 4.2: Stacking and splitting
#------------------------------------
print("\n--- Task 4.2: Stacking and splitting ---")

# given arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# 1. vertical stack of 3X3 array
v_stack = np.vstack((arr1, arr2, arr3))
print("\nVertical stack of 3X3 array:\n",v_stack)

# 2.horizontal stack of 1D array
h_stack = np.hstack((arr1, arr2, arr3))
print("\nHorizontal stack of 1D array:\n",h_stack)

# array from 1 to 12 and
arr = np.arange(1, 13)
print("\nArray from 1 to 12:",arr)

# Spliting array into 4 equal parts
arr_split = np.split(arr, 4)

print("\nSplit it into 4 equal parts:\n", arr_split)

# 4x4 array with values 1-16
arr_4_by_4 = np.arange(1, 17).reshape(4, 4) #reshaping into 4X4
print("\n4x4 array with values 1-16:\n",arr_4_by_4)
print("\nshape:",arr_4_by_4.shape)

# Spliting the array horizontally into 2 parts
# used gpt to know how to show the array
h_array = np.hsplit(arr_4_by_4, 2)
      
print("\nSpliting the array horizontally into 2 parts:")
print(h_array[0])
print(h_array[1])  



--- Task 4.2: Stacking and splitting ---

Vertical stack of 3X3 array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal stack of 1D array:
 [1 2 3 4 5 6 7 8 9]

Array from 1 to 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Split it into 4 equal parts:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

4x4 array with values 1-16:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

shape: (4, 4)

Spliting the array horizontally into 2 parts:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [50]:
## Exercise 5: Statistical Operations (15 points)

### Task 5.1: Basic statistics (7 points)

"""
Given `arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])`:

Calculate and print:
1. Sum of all elements
2. Mean (average)
3. Median
4. Standard deviation
5. Variance
6. Minimum value
7. Maximum value
8. Index of minimum value
9. Index of maximum value

**Your Code:**
```python
"""    
# Write your code here

## Exercise 5: Statistical Operations
print("="*60)
print("Exercise 5: Statistical Operations")
print("="*60)
#--------------------------------
## Task 5.1: Basic statistics
#--------------------------------
print("\n--- ask 5.1: Basic statistics ---")

# Given array
arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])
print("\nOriginal Array:\n", arr)

# statistical calculation

# 1. Sum of all elements
total_sum = np.sum(arr)

# 2. Mean (average) value of array
mean_val = np.mean(arr)
                   
# 3.Median value of array
median_val = np.median(arr)

# 4. Standard deviation of array
std = np.std(arr)

# 5. Variance value 
variance = np.var(arr) # used g

# 6. Minimum value in the array
min_val = np.min(arr)

# 7. Maximum value in the array 
max_val = np.max(arr)

# 8. Index of minimum value
min_index = np.argmin(arr) #used gpt

# 9. Index of maximum value
max_index = np.argmax(arr)

# Displaying result
print("\nSum:", total_sum)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard deviation:", std)
print("Variance:", variance)
print("Minimum value:", min_val)
print("Maximum value:", max_val)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Exercise 5: Statistical Operations

--- ask 5.1: Basic statistics ---

Original Array:
 [12 45 23 67 34 89 56 78 90 31]

Sum: 525
Mean: 52.5
Median: 50.5
Standard deviation: 26.424420523447623
Variance: 698.25
Minimum value: 12
Maximum value: 90
Index of minimum value: 0
Index of maximum value: 8


In [51]:
### Task 5.2: Axis-based statistics (8 points)

"""
Create a 3x3 array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```

Calculate:
1. Sum of all elements
2. Sum along axis 0 (column-wise sum)
3. Sum along axis 1 (row-wise sum)
4. Mean along axis 0
5. Mean along axis 1
6. Maximum values along axis 0
7. Maximum values along axis 1

**Your Code:**
```python
"""
# Write your code here

#----------------------------------
## Task 5.2: Axis-based statistics
#----------------------------------
print("\n--- Task 5.2: Axis-based statistics ---")

# 3x3 array
arr_3x3 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("\nOriginal Array:\n",arr_3x3)

# 1. Sum of all elements
total_sum = np.sum(arr_3x3)

# 2. column-wise sum (axis = 0)
col_sum = np.sum(arr_3x3, axis = 0)

#3. row-wise sum (axis = 1)
row_sum = np.sum(arr_3x3, axis = 1)

# 4. Mean along axis 0
col_mean = np.mean(arr_3x3, axis = 0)

# 5. Mean along axis 1
row_mean = np.mean(arr_3x3, axis = 1)

# 6. Maximum values along axis 0\
max_col = np.max(arr_3x3, axis = 0)

# 7. Maximum values along axis 1
max_row = np.max(arr_3x3, axis = 1)

#  Displaying Result
print("\nSum of all elements:", total_sum)
print("\ncolumn-wise sum:", col_sum)
print("\nrow-wise sum:", row_sum)
print("\ncolumn-wise mean:", col_mean)
print("\nrow-wise mean:", row_mean)
print("\ncolumn-wise maximum:", max_col)
print("\nrow-wise maximum:", max_row)



--- Task 5.2: Axis-based statistics ---

Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Sum of all elements: 450

column-wise sum: [120 150 180]

row-wise sum: [ 60 150 240]

column-wise mean: [40. 50. 60.]

row-wise mean: [20. 50. 80.]

column-wise maximum: [70 80 90]

row-wise maximum: [30 60 90]


In [52]:
## Exercise 6: Real-World Application - Student Grade Analysis (25 points)

"""You are given grade data for 5 students across 4 subjects (Math, Science, English, History):

```python

grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])
"""
"""
**Tasks:**

1. **Calculate the average grade for each student** (5 points)
   - Output should show Student 1: X.XX, Student 2: Y.YY, etc.

2. **Calculate the average grade for each subject** (5 points)
   - Output: Math: X.XX, Science: Y.YY, etc.

3. **Find the highest and lowest grades in each subject** (5 points)
   - Output for each subject: Highest = X, Lowest = Y

4. **Identify students with an average grade above 85** (3 points)
   - Print student number and their average

5. **Calculate the overall class average** (2 points)
   - Average of all grades across all students

6. **Normalize all grades to a scale of 0-10** (5 points)
   - Use min-max normalization formula: (value - min) / (max - min) * 10
   - Print the normalized grades array

**Bonus:** Identify the top-performing student (+2 points)

**Your Code:**
python
"""      


## Exercise 6: Real-World Application - Student Grade Analysis
print("="*60)
print("Exercise 6: Student Grade Analysis")
print("="*60)

# Given matrix
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])

# There are 4 subjects
subject_name = ["Maths", "Science", "English", "History"]
print("\nStudent grades:\n",grades)
print("shape:", grades.shape)

# 1. average grade for each student(axis = 1)
print("\n--- Task 1: Student Averages ---")
student_avg = np.mean(grades, axis = 1) #each student marks are row wise

# used gpt to print output in required format
for student_num, avg in enumerate(student_avg, start=1):
    # +1 converts 0-based index to student number
    print(f"Student {student_num}: {avg:.2f}")

 # 2. average grade for each subject(axis = 0)
print("\n--- Task 2: Subject Averages ---")
subject_avg = np.mean(grades, axis = 0) #each subject average, column wise

# used gpt to print output in required format
for subject, avg in zip(subject_name, subject_avg):
    print(f"{subject}: {avg:.2f}")

# 3. highest and lowest grades in each subject(axis = 0)
print("\n--- Task 3: Highest and Lowest per subject ---")
subject_max = np.max(grades, axis = 0) # highest grade in subjects
subject_min = np.min(grades, axis = 0) # lowest grade in subject

# Loop to display reslut in required format
for subject, high, low in zip(subject_name, subject_max, subject_min):
    print(f"{subject}: Highest = {high}, Lowest = {low}")

#Students with average above 85 
print("\n--- Task 4 : Students with average above 85 ---")

above_85_avg = student_avg > 85
for i, avg in enumerate(student_avg[above_85_avg], start=1):
    # used gpt to display required output
    # np.where(above_85_mask)[0] gives indices of True values
    # i-1 is used because enumerate starts from 1
    student_num = np.where(above_85_avg)[0][i-1] + 1
    print(f"Student {student_num}: {avg:.2f}")

# overall class average
class_avg = np.mean(grades)
print("\n--- Task 5 : overall class average ---")
print("Overall average:",class_avg)

# Normalizing all grades to a scale of 0-10
# minimum of grades
min_grade = np.min(grades)
#  maximum of grades
max_grade = np.max(grades)

# Using min-max normalization formula
normalized_grades = (grades - min_grade) / (max_grade - min_grade) * 10

print("\n--- Task 6 : normalized grades array ---")
print(np.round(normalized_grades, 2))

# Identifying the top-performing student
print("\n--- bonus : top-performing student ---")
top_student = np.argmax(student_avg) + 1
print("Student",top_student)



"""
**Expected Output Format:**
```
--- Task 1: Student Averages ---
Student 1: XX.XX
...

--- Task 2: Subject Averages ---
Math: XX.XX
...

(Continue for all tasks)

"""

Exercise 6: Student Grade Analysis

Student grades:
 [[85 90 78 88]
 [92 88 95 90]
 [76 82 80 75]
 [88 85 90 92]
 [95 92 88 94]]
shape: (5, 4)

--- Task 1: Student Averages ---
Student 1: 85.25
Student 2: 91.25
Student 3: 78.25
Student 4: 88.75
Student 5: 92.25

--- Task 2: Subject Averages ---
Maths: 87.20
Science: 87.40
English: 86.20
History: 87.80

--- Task 3: Highest and Lowest per subject ---
Maths: Highest = 95, Lowest = 76
Science: Highest = 92, Lowest = 82
English: Highest = 95, Lowest = 78
History: Highest = 94, Lowest = 75

--- Task 4 : Students with average above 85 ---
Student 1: 85.25
Student 2: 91.25
Student 4: 88.75
Student 5: 92.25

--- Task 5 : overall class average ---
Overall average: 87.15

--- Task 6 : normalized grades array ---
[[ 5.   7.5  1.5  6.5]
 [ 8.5  6.5 10.   7.5]
 [ 0.5  3.5  2.5  0. ]
 [ 6.5  5.   7.5  8.5]
 [10.   8.5  6.5  9.5]]

--- bonus : top-performing student ---
Student 5


'\n**Expected Output Format:**\n```\n--- Task 1: Student Averages ---\nStudent 1: XX.XX\n...\n\n--- Task 2: Subject Averages ---\nMath: XX.XX\n...\n\n(Continue for all tasks)\n\n'

In [45]:
## Exercise 7: Challenge - Sales Data Analysis (30 points)

"""You are analyzing sales data for a company with 4 products over 6 months:

python
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])
**Tasks:**

1. **Calculate total sales for each product** (5 points)
   - Sum across all months for each product

2. **Calculate total sales for each month** (5 points)
   - Sum across all products for each month (Jan to Jun)

3. **Identify the month with the highest total sales** (4 points)
   - Print the month name and total sales

4. **Calculate the growth rate for each product** (6 points)
   - Growth rate = ((Last month - First month) / First month) × 100
   - Print as percentage for each product

5. **Find products with average monthly sales greater than 120k** (4 points)
   - Calculate average for each product
   - Print products meeting the criteria

6. **Calculate quarter-wise sales** (6 points)
   - Q1: January-March
   - Q2: April-June
   - Print sales for each product in each quarter

**Bonus:** Predict next month (July) sales for each product (+5 points)
- Use a simple method: average of last 2 months + average monthly growth

**Your Code:**
python
"""

## Exercise 7: Challenge - Sales Data Analysis
print("="*50)
print("Exercise 7: Challenge - Sales Data Analysis")
print("="*50)

# sales data(rows = products, columns = months) 
sales_data = np.array([
    [120, 135, 150, 145, 160, 175], # product A
    [90, 95, 100, 110, 115, 120], # product B
    [150, 145, 155, 160, 170, 180], # product C
    [80, 85, 82, 88, 92, 95] # product D
])

# Product names in the sales data          
product_names = np.array(["Product A", "Product B", "Product C", "Product D"])
# Month names in the sales data             
month_names = np.array(["Jan", "Feb","Mar", "Apr", "May", "Jun"])

#---------------------------------
# 1. Total sales for each product 
#---------------------------------
product_total_sales = np.sum(sales_data, axis = 1) # (axis = 1, row wise)
print("\n--- Task 1 : Total sales for each product ---")
# Used gpt to know how to use zip 
# used zip to pair each product with its total sales
# and display them together
for product, total in zip(product_names, product_total_sales):
    print(f"{product}: {total}")
#---------------------------------
# 2. Total sales for each month
#---------------------------------
monthly_total_sales = np.sum(sales_data, axis = 0) # (axis = 0, column wise)
                   
print("\n--- Task 2 : Total sales for each month ---")
# use zip to pair each month with its total sales
# and display them together
for month, total in zip(month_names, monthly_total_sales):
    print(f"{month}: {total}")

#--------------------------------------
# 3. Month with the highest total sales
#--------------------------------------
print("\n--- Task 3 : Month with the highest total sales ---")
# usign argmax to get highest index value
highest_month = np.argmax(monthly_total_sales)
    
print("\nHighest sales month:", month_names[highest_month])
print("with sales", monthly_total_sales[highest_month])

#------------------------------------
# 4. Growth rate for each product
#------------------------------------

first_month_sales = sales_data[:, 0] # january sales
last_month_sales = sales_data[:, -1] # june sales

# using Growth rate formula
growth_rate = ((last_month_sales - first_month_sales) / first_month_sales ) * 100

print("\n--- Task 4 : Growth rate for each product ---")
# Use zip to pair each product name with its growth rate
# and display them together
for product, growth in zip(product_names, growth_rate):
    print(f"{product}: {growth:.2f}%")

#---------------------------------------------------
# 5. Products with average monthly sales > 120k 
#---------------------------------------------------
# Calculating average monthly sale for each product
product_avg_sales =np.mean(sales_data, axis = 1) # row wise
# checking which products have avg sale > 120k
above_120_avg = product_avg_sales > 120 # condition

print("\n--- Task 5 : Products with average monthly sales > 120k ---")
# use zip to display only products with avg sale >120k
for product, avg in zip(product_names[above_120_avg], growth_rate[above_120_avg]):
    print(f"{product}: {avg:.2f}%")

#--------------------------------------------------
# 6. Quarter-wise sales
#--------------------------------------------------

# Q1: January-March(columns 0 to 2)
# used gpt to get Q1
q1_sales = np.sum(sales_data[:, 0:3], axis = 1)
# Q2: April to June (columns 3 to 5)
q2_sales = np.sum(sales_data[:, 3:6], axis = 1)

print("\n--- Task 6 : Quarter-wise sales ---")

# use zip to display Q1 and Q2 sales for each product
for product, q1, q2 in zip(product_names, q1_sales, q2_sales):
    print(f"{product} -> Q1: {q1}, Q2 : {q2}")
    
#-------------------------------------------------------
# Bonus:Predict next month (July) sales for each product
#-------------------------------------------------------
# used gpt to understand row-wise mean using vectorized slicing and aggregation.
# calculate average of last two months
last_two_month_avg = np.mean(sales_data[:, -2:], axis=1)
# calculate average monthly growth
average_monthly_growth = (last_month_sales - first_month_sales) / (sales_data.shape[1] - 1)
#  predicting July sales
predicted_july_sales = last_two_month_avg + average_monthly_growth

print("\n--- Bonus : Predicted July sales ---")
# use zip to dispaly predicted sales for each product
for product, prediction in zip(product_names, predicted_july_sales):
    print(f"{product}: {prediction:.2f}")


Exercise 7: Challenge - Sales Data Analysis

--- Task 1 : Total sales for each product ---
Product A: 885
Product B: 630
Product C: 960
Product D: 522

--- Task 2 : Total sales for each month ---
Jan: 440
Feb: 460
Mar: 487
Apr: 503
May: 537
Jun: 570

--- Task 3 : Month with the highest total sales ---

Highest sales month: Jun
with sales 570

--- Task 4 : Growth rate for each product ---
Product A: 45.83%
Product B: 33.33%
Product C: 20.00%
Product D: 18.75%

--- Task 5 : Products with average monthly sales > 120k ---
Product A: 45.83%
Product C: 20.00%

--- Task 6 : Quarter-wise sales ---
Product A -> Q1: 405, Q2 : 480
Product B -> Q1: 285, Q2 : 345
Product C -> Q1: 450, Q2 : 510
Product D -> Q1: 247, Q2 : 275

--- Bonus : Predicted July sales ---
Product A: 178.50
Product B: 123.50
Product C: 181.00
Product D: 96.50
